name: Main Workflow

on: push

jobs:
  build:

    name: Lint and Test

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7]

    steps:
    - uses: actions/checkout@master

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
        poetry shell
    
    - name: Pylint
      run: poetry run pylint traindisplay test -d C0303,C0412,C0330,E1120,R0201,E0213,R0903,R0801
    
    - name: Pydocstyle
      run: poetry run pydocstyle traindisplay test/*.py --verbose
    
    - name: Black
      run: poetry run black traindisplay test --check --verbose
    
    - name: Pytest
      run: poetry run pytest . -v
