name: Main Workflow

on: push

jobs:
  build:
    name: Lint and Test

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7]

    steps:
      - uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          version: ${{ matrix.python-version }}

      - name: Install Apt Dependencies
        run: |
          sudo apt-get build-dep python-pygame

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
          poetry shell

      - name: Pydocstyle
        run: poetry run pydocstyle traindisplay test/*.py --verbose

      - name: Black
        run: poetry run black traindisplay test --check --verbose

      - name: Pytest
        run: poetry run pytest . -v
