name: Main Workflow

on: push

jobs:
  build:
    name: Push

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7]

    steps:
      - uses: actions/checkout@master

      - name: Install Apt Dependencies
        run: |
          sudo apt install \
            libsdl-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev \
            libjpeg-dev \
            libpng-dev \
            libportmidi-dev

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          version: ${{ matrix.python-version }}

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install poetry
          pip install --editable .[dev]

      - name: Black
        run: black traindisplay test --check --verbose

      - name: Pytest
        run: pytest . -v
